source 'http://rubygems.org'
ruby '2.1.2'

gem 'json'

gem 'goodreads', '~> 0.3.0'
gem 'omniauth-goodreads', :git => "https://github.com/sandboxws/omniauth-goodreads.git"

gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
# gem 'spring',        group: :development
gem 'bootstrap-sass'
gem 'high_voltage'
gem 'thin'
group :production do
  gem 'rails_12factor'
  gem 'pg'
  end
group :development do
  gem 'sqlite3'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'selenium-webdriver'
end
