# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0355b90870ae8c4cf1dbc2d211dd981781f43e115b811170a57be6a10c15d68e591e21bf995b418943725857db6966da5f473fdb6a771f522f29156b4ea9962a

test:
  secret_key_base: 5d903c3d1022419b69de2e23b84ec6842449453647e8f75c9c9ce5773a213ec02dc24c52a14bc71b96617e456c3ca6b1a6c2dffe9e6aaab39d8f7d80230f3e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
